# Generated by Django 5.0.6 on 2024-05-24 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_alter_author_headshot_alter_book_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='salutation',
        ),
    ]
