# Generated by Django 4.2.13 on 2024-05-24 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_remove_author_salutation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['-id']},
        ),
    ]
